{
 "title": "GKE + Nvidia DCGM",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{exported_container!=\"\"}",
     "legendFormat": "{{Hostname}} {{modelName}}-{{gpu}} {{exported_container}}"
    }
   ]
  },
  {
   "title": "GPU Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{exported_container!=\"\"}",
     "legendFormat": "{{Hostname}} {{modelName}}-{{gpu}} {{exported_container}}"
    }
   ]
  },
  {
   "title": "GPU SM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_SM_ACTIVE{exported_container!=\"\"}",
     "legendFormat": "{{Hostname}} {{modelName}}-{{gpu}} {{exported_container}}"
    }
   ]
  },
  {
   "title": "GPU SM Occupancy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_SM_OCCUPANCY{exported_container!=\"\"}",
     "legendFormat": "{{Hostname}} {{modelName}}-{{gpu}} {{exported_container}}"
    }
   ]
  },
  {
   "title": "GPU Tensor Engine Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{exported_container!=\"\"}",
     "legendFormat": "{{Hostname}} {{modelName}}-{{gpu}} {{exported_container}}"
    }
   ]
  },
  {
   "title": "FP32 Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_FP32_ACTIVE{exported_container!=\"\"}",
     "legendFormat": "{{Hostname}} {{modelName}}-{{gpu}} {{exported_container}}"
    }
   ]
  },
  {
   "title": "FP64 Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_FP32_ACTIVE{exported_container!=\"\"}",
     "legendFormat": "{{Hostname}} {{modelName}}-{{gpu}} {{exported_container}}"
    }
   ]
  },
  {
   "title": "FP16 Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_FP16_ACTIVE{exported_container!=\"\"}",
     "legendFormat": "{{Hostname}} {{modelName}}-{{gpu}} {{exported_container}}"
    }
   ]
  },
  {
   "title": "PCIe Tx Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PCIE_TX_BYTES{exported_container!=\"\"}",
     "legendFormat": "{{Hostname}} {{modelName}}-{{gpu}} {{exported_container}}"
    }
   ]
  },
  {
   "title": "PCIe Tx Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PCIE_TX_BYTES{exported_container!=\"\"}",
     "legendFormat": "{{Hostname}} {{modelName}}-{{gpu}} {{exported_container}}"
    }
   ]
  },
  {
   "title": "NvLink Tx Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_NVLINK_TX_BYTES{exported_container!=\"\"}",
     "legendFormat": "{{Hostname}} {{modelName}}-{{gpu}} {{exported_container}}"
    }
   ]
  },
  {
   "title": "NvLink Rx Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_NVLINK_RX_BYTES{exported_container!=\"\"}",
     "legendFormat": "{{Hostname}} {{modelName}}-{{gpu}} {{exported_container}}"
    }
   ]
  },
  {
   "title": "GPU Memory Copy Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{exported_container!=\"\"}",
     "legendFormat": "{{Hostname}} {{modelName}}-{{gpu}} {{exported_container}}"
    }
   ]
  }
 ]
}